version: '3'

services:
  solvisremotefetcher:
    build: .
    restart: unless-stopped
    env_file: .environment

  # If you want to use a local InfluxDB container
  # influxdb:
  #   image: influxdb:alpine
  #   restart: unless-stopped
  #   ports:
  #     - "8086:8086"
  #   volumes:
  #     - ./influx:/var/lib/influxdb
  #   environment:
  #     - INFLUXDB_RETENTION_ENABLED=false
  #     - INFLUXDB_REPORTING_DISABLED=true
  #     - INFLUXDB_HTTP_ENABLED=true
  #     - INFLUXDB_HTTP_AUTH_ENABLED=true

# If you want to attach to an existing network which already hosts an InfluxDB
# networks:
#   default:
#     external:
#       name: influx_net
